name: UI testing

on:
  workflow_dispatch:
    inputs:
      grid_url:
        required: true
        type: string
        description: Grid to run tests on (local by default)
        default: http://localhost:4444

      chrome_131_0:
        description: 'Chrome (131.0)'
        required: false
        type: boolean

      edge_131_0:
        description: 'Edge (131.0)'
        required: false
        type: boolean

jobs:
  TestChrome_131_0:
    name: Test Chrome 131.0
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.chrome_131_0 == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Launch standalone grid - Chrome
        if: ${{ contains(github.event.inputs.grid_url, 'localhost') }}
        run: |
          docker run --name grid_container -d -p 4444:4444 --shm-size=2gb selenium/standalone-chrome:131.0-chromedriver-131.0-grid-4.27.0-20250101

      - name: Run Tests
        run: |
          export BROWSER=chrome
          export GRID_URL=${{ github.event.inputs.grid_url }}
          
          mvn -q test
          
          # Tear down grid if exists
          docker stop grid_container || true

  TestEdge_131_0:
    name: Test Edge 131.0
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.edge_131_0 == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Launch standalone grid - Edge
        if: ${{ contains(github.event.inputs.grid_url, 'localhost') }}
        run: |
          docker run --name grid_container -d -p 4444:4444 --shm-size=2gb selenium/standalone-edge:131.0-edgedriver-131.0-grid-4.27.0-20250101

      - name: Run Tests
        run: |
          export BROWSER=edge
          export GRID_URL=${{ github.event.inputs.grid_url }}
          
          mvn test -q
          
          # Tear down grid if exists
          docker stop grid_container || true