name: 'Test Report'

on:
  workflow_run:
    workflows: ['Smoke testing']           # Adjusted to match your smoke testing workflow name
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: test-results

      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: Smoke Test Report          # Adjusted name for the check run
          path: 'target/surefire-reports/TEST-*.xml'
          reporter: java-junit
